Content-Type: multipart/mixed; boundary="------------U9QF3bpk1U3jv0M9fk485sPX"
Message-ID: <af91a6a5-94db-437f-bf7a-c51384f6c7da@gmail.com>
Date: Wed, 13 Dec 2023 14:19:31 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: vi-x-KieuCu.[Chuan]
To: lyhai1502.work@gmail.com
From: "lyhai1502.work@gmail.com" <lyhai1502.work@gmail.com>
Subject: hello

This is a multi-part message in MIME format.
--------------U9QF3bpk1U3jv0M9fk485sPX
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

helo

--------------U9QF3bpk1U3jv0M9fk485sPX
Content-Type: text/plain; charset=UTF-8; name="gitignore.txt"
Content-Disposition: attachment; filename="gitignore.txt"
Content-Transfer-Encoding: base64

dGFyZ2V0LwohLm12bi93cmFwcGVyL21hdmVuLXdyYXBwZXIuamFyCiEqKi9zcmMvbWFpbi8q
Ki90YXJnZXQvCiEqKi9zcmMvdGVzdC8qKi90YXJnZXQvCgojIyMgSW50ZWxsaUogSURFQSAj
IyMKLmlkZWEvbW9kdWxlcy54bWwKLmlkZWEvamFyUmVwb3NpdG9yaWVzLnhtbAouaWRlYS9j
b21waWxlci54bWwKLmlkZWEvbGlicmFyaWVzLwoqLml3cwoqLmltbAoqLmlwcgoKIyMjIEVj
bGlwc2UgIyMjCi5hcHRfZ2VuZXJhdGVkCi5jbGFzc3BhdGgKLmZhY3RvcnlwYXRoCi5wcm9q
ZWN0Ci5zZXR0aW5ncwouc3ByaW5nQmVhbnMKLnN0czQtY2FjaGUKCiMjIyBOZXRCZWFucyAj
IyMKL25icHJvamVjdC9wcml2YXRlLwovbmJidWlsZC8KL2Rpc3QvCi9uYmRpc3QvCi8ubmIt
Z3JhZGxlLwpidWlsZC8KISoqL3NyYy9tYWluLyoqL2J1aWxkLwohKiovc3JjL3Rlc3QvKiov
YnVpbGQvCgojIyMgVlMgQ29kZSAjIyMKLnZzY29kZS8KCiMjIyBNYWMgT1MgIyMjCi5EU19T
dG9yZQ==

--------------U9QF3bpk1U3jv0M9fk485sPX--

