Content-Type: multipart/mixed; boundary="------------1702351905300"
To: lyhai1502.work@gmail.com
Cc: lyhai1502@gmail.com
From: hello2@gmail.com <hello2@gmail.com>
Subject: Test

This is a multi-part message in MIME format.
--------------1702351905300
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

test

--------------1702351905300
Content-Type: text/plain; charset=UTF-8; name="/Users/vanlyhai/Downloads/gitignore.txt"
Content-Disposition: attachment; filename="gitignore.txt"
Content-Transfer-Encoding: base64

dGFyZ2V0LwohLm12bi93cmFwcGVyL21hdmVuLXdyYXBwZXIuamFyCiEqKi9zcmMvbWFpbi8q
Ki90YXJnZXQvCiEqKi9zcmMvdGVzdC8qKi90YXJnZXQvCgojIyMgSW50ZWxsaUogSURFQSAj
IyMKLmlkZWEvbW9kdWxlcy54bWwKLmlkZWEvamFyUmVwb3NpdG9yaWVzLnhtbAouaWRlYS9j
b21waWxlci54bWwKLmlkZWEvbGlicmFyaWVzLwoqLml3cwoqLmltbAoqLmlwcgoKIyMjIEVj
bGlwc2UgIyMjCi5hcHRfZ2VuZXJhdGVkCi5jbGFzc3BhdGgKLmZhY3RvcnlwYXRoCi5wcm9q
ZWN0Ci5zZXR0aW5ncwouc3ByaW5nQmVhbnMKLnN0czQtY2FjaGUKCiMjIyBOZXRCZWFucyAj
IyMKL25icHJvamVjdC9wcml2YXRlLwovbmJidWlsZC8KL2Rpc3QvCi9uYmRpc3QvCi8ubmIt
Z3JhZGxlLwpidWlsZC8KISoqL3NyYy9tYWluLyoqL2J1aWxkLwohKiovc3JjL3Rlc3QvKiov
YnVpbGQvCgojIyMgVlMgQ29kZSAjIyMKLnZzY29kZS8KCiMjIyBNYWMgT1MgIyMjCi5EU19T
dG9yZQ==

--------------1702351905300--

