Content-Type: multipart/mixed; boundary="------------0ZX459ulQQo3MXKk14LV63ol"
Message-ID: <15ced1f2-25ac-4ccf-8062-8b8ae6f1ceb3@gmail.com>
Date: Sun, 10 Dec 2023 20:19:03 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: xuanchien@gmail.com
From: =?UTF-8?B?TmfDtCBYdcOibiBDaGnhur9u?= <xuanchien@gmail.com>

This is a multi-part message in MIME format.
--------------0ZX459ulQQo3MXKk14LV63ol
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit


--------------0ZX459ulQQo3MXKk14LV63ol
Content-Type: text/plain; charset=UTF-8; name="123.txt"
Content-Disposition: attachment; filename="123.txt"
Content-Transfer-Encoding: base64

VEVzdA==

--------------0ZX459ulQQo3MXKk14LV63ol--

