Content-Type: multipart/mixed; boundary="------------0K0chc5UgCvZ0Gc9IE37Y40J"
Message-ID: <2de73511-fab7-4ce5-a9a7-891ef9a3bd34@gmail.com>
Date: Sun, 10 Dec 2023 19:05:56 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-US
To: xuanchien@gmail.com
From: =?UTF-8?B?TmfDtCBYdcOibiBDaGnhur9u?= <xuanchien@gmail.com>

This is a multi-part message in MIME format.
--------------0K0chc5UgCvZ0Gc9IE37Y40J
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit


--------------0K0chc5UgCvZ0Gc9IE37Y40J
Content-Type: text/plain; charset=UTF-8; name="123.txt"
Content-Disposition: attachment; filename="123.txt"
Content-Transfer-Encoding: base64

VEVzdA==

--------------0K0chc5UgCvZ0Gc9IE37Y40J--

